{% set version = "0.9.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tern/tern_{{ version }}.tar.gz
  sha256: 13d1dd0d3d8263812e30c61da9908daa87c673a63bde0349f1c7486416814e2f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.4.0
    - r-mass >=7.3_60
    - r-rdpack >=2.4
    - r-broom >=0.5.4
    - r-car >=3.0_13
    - r-checkmate >=2.1.0
    - r-cowplot >=1.0.0
    - r-dplyr >=1.0.0
    - r-emmeans >=1.10.4
    - r-forcats >=1.0.0
    - r-formatters >=0.5.11
    - r-ggplot2 >=3.5.0
    - r-gridextra >=2.0.0
    - r-gtable >=0.3.0
    - r-labeling
    - r-lifecycle >=0.2.0
    - r-magrittr >=1.5
    - r-nestcolor >=0.1.1
    - r-rlang >=1.1.0
    - r-rtables >=0.6.13
    - r-scales >=1.2.0
    - r-survival >=3.8_3
    - r-tibble >=2.0.0
    - r-tidyr >=0.8.3
  run:
    - r-base >=4.4.0
    - r-mass >=7.3_60
    - r-rdpack >=2.4
    - r-broom >=0.5.4
    - r-car >=3.0_13
    - r-checkmate >=2.1.0
    - r-cowplot >=1.0.0
    - r-dplyr >=1.0.0
    - r-emmeans >=1.10.4
    - r-forcats >=1.0.0
    - r-formatters >=0.5.11
    - r-ggplot2 >=3.5.0
    - r-gridextra >=2.0.0
    - r-gtable >=0.3.0
    - r-labeling
    - r-lifecycle >=0.2.0
    - r-magrittr >=1.5
    - r-nestcolor >=0.1.1
    - r-rlang >=1.1.0
    - r-rtables >=0.6.13
    - r-scales >=1.2.0
    - r-survival >=3.8_3
    - r-tibble >=2.0.0
    - r-tidyr >=0.8.3

test:
  commands:
    - $R -e "library('tern')"           # [not win]
    - "\"%R%\" -e \"library('tern')\""  # [win]

about:
  home: https://insightsengineering.github.io/tern/, https://github.com/insightsengineering/tern/
  license: Apache-2.0
  summary: Table, Listings, and Graphs (TLG) library for common outputs used in clinical trials.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
